# Generated by Django 5.2.8 on 2025-11-10 00:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]),
            preserve_default=False,
        ),
    ]
