# Generated by assistant to remove unique constraint on Comment
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
